#!/usr/bin/env bash

set -e

ROOT_PATH=/opt/halyard
export GEM_PATH=$ROOT_PATH/vendor
BIN_PATH=$GEM_PATH/bin
REPO_PATH=$ROOT_PATH/repo
ENV_PATH=$ROOT_PATH/environments

gem list --installed bundler >/dev/null || gem install --no-document --install-dir $GEM_PATH bundler

$BIN_PATH/bundle install --path=$GEM_PATH --binstubs=$BIN_PATH --gemfile=$REPO_PATH/Gemfile --without=development

(cd $REPO_PATH && $BIN_PATH/librarian-puppet install --path=modules)

sudo $BIN_PATH/puppet apply --environment=production --environmentpath=$ENV_PATH $ENV_PATH/manifests --debug
