#!/usr/bin/env bash

set -euo pipefail

ROOTDIR=/opt/halyard

echo 'Checking for pending software updates'
softwareupdate -i -a

echo 'Checking for Xcode command line tools'
set +e
xcode-select -p &>/dev/null
if [ "$?" != "0" ] ; then
    echo 'Please follow the prompt to install Xcode command line tools'
    xcode-select --install &>/dev/null
    while true ; do
        sleep 5
        xcode-select -p &>/dev/null && break
    done
fi
set -e

[[ -e $ROOTDIR ]] || sudo mkdir -p $ROOTDIR

if [[ -e $ROOTDIR/repo/README.md ]] ; then
    (cd $ROOTDIR/repo && git pull)
else
    sudo git clone git://github.com/halyard/halyard $ROOTDIR/repo
fi

[[ -e $ROOTDIR/environments ]] || sudo mkdir -p $ROOTDIR/environments
[[ -e $ROOTDIR/environments/production ]] || sudo ln -s $ROOTDIR/repo $ROOTDIR/environments/production

caffeinate -di sudo $ROOTDIR/repo/meta/halyard

