#!/usr/bin/env bash

set -euo pipefail

PUPPET_VERSION=1.10.1-1
ROOTDIR=/opt/halyard

echo 'Checking for pending software updates'
softwareupdate -i -a

echo 'Checking for Xcode command line tools'
set +e
xcode-select -p &>/dev/null
if [ "$?" != "0" ] ; then
    echo 'Please follow the prompt to install Xcode command line tools'
    xcode-select --install &>/dev/null
    while true ; do
        sleep 5
        xcode-select -p &>/dev/null && break
    done
fi
set -e

[[ -e $ROOTDIR ]] || sudo mkdir -p $ROOTDIR

if [[ -e $ROOTDIR/repo/README.md ]] ; then
    (cd $ROOTDIR/repo && git pull)
else
    sudo git clone git://github.com/halyard/halyard $ROOTDIR/repo
fi

[[ -e $ROOTDIR/environments ]] || sudo mkdir -p $ROOTDIR/environments
[[ -e $ROOTDIR/environments/production ]] || sudo ln -s $ROOTDIR/repo $ROOTDIR/environments/production

if [[ ! -e /opt/puppetlabs/bin/puppet ]] ; then
    puppet_tmpdir="$(mktemp -d)"
    puppet_url="https://downloads.puppetlabs.com/mac/10.12/PC1/x86_64/puppet-agent-${PUPPET_VERSION}.osx10.12.dmg"
    puppet_dmg="${puppet_tmpdir}/puppet-agent.dmg"
    puppet_mount="${puppet_tmpdir}/puppet-agent.volume"
    puppet_installer="${puppet_mount}/puppet-agent-${PUPPET_VERSION}-installer.pkg"
    curl -sLo "$puppet_dmg" "$puppet_url"
    hdiutil attach -puppetstrings -nobrowse -readonly -noidme -mountpoint "$puppet_mount" "${puppet_dmg}"
    sudo installer -pkg "${puppet_installer}" -target /
    hdiutil unmount "$puppet_mount"
fi

caffeinate -di sudo -i $ROOTDIR/repo/meta/halyard

