#!/usr/bin/env bash

ROOTDIR=/opt/halyard

echo 'Checking for pending software updates'
softwareupdate -i -a

echo 'Checking for Xcode command line tools'
xcode-select -p &>/dev/null
if [ "$?" != "0" ] ; then
    echo 'Please follow the prompt to install Xcode command line tools'
    xcode-select --install &>/dev/null
    while true ; do
        sleep 5
        xcode-select -p &>/dev/null && break
    done
fi

set -e

[[ -e $ROOTDIR ]] || sudo mkdir -p $ROOTDIR
[[ "$(/usr/bin/stat -f"%Su:%Sg" $ROOTDIR)" == "${USER}:staff" ]] ||  sudo chown ${USER}:staff $ROOTDIR
if [[ -e $ROOTDIR/repo/README.md ]] ; then
    (cd $ROOTDIR/repo && git pull)
else
    git clone git://github.com/halyard/halyard $ROOTDIR/repo
fi

caffeinate -di $ROOTDIR/repo/meta/halyard

