#!/bin/sh
# Make sure all our local dependencies are available.

set -e

#Add fake group to fix GID/domain issues (https://github.com/boxen/our-boxen/issues/235)
GID="$(id -g)"
USERNAME="$(id -u -nr)"
if !(grep "$GID" /etc/group >/dev/null) ; then
  echo "Adding GID ($GID) for $USERNAME into /etc/group"
  sudo sh -c "echo $USERNAME:*:$GID:$USERNAME >> /etc/group"
fi

INSTALL_DIR=.rubybin

if [[ ! -e .rubybin/bundle ]]; then
  sudo /usr/bin/gem install bundler --no-document --bindir=$INSTALL_DIR
fi

# We don't want old config hanging around.

rm -rf .bundle/config
rm -rf .librarian/puppet/config

$INSTALL_DIR/bundle install --binstubs bin --path .bundle --quiet "$@"


# Fix the binstubs to use system ruby
find bin -not -path 'bin/\.*' -type f -print0 | xargs -0 /usr/bin/sed -i '' 's|/usr/bin/env ruby|/usr/bin/ruby|g'
