#!/bin/sh
# Make sure all our local dependencies are available.

set -e

#Add fake group to fix GID/domain issues (https://github.com/boxen/our-boxen/issues/235)
GID="$(id -g)"
USERNAME="$(id -u -nr)"
if !(grep "$GID" /etc/group >/dev/null) ; then
  echo "Adding GID ($GID) for $USERNAME into /etc/group"
  sudo sh -c "echo $USERNAME:*:$GID:$USERNAME >> /etc/group"
fi

# FIX: only sudo if gem home isn't writable

(/usr/bin/gem list -i bundler > /dev/null) || {
  /usr/bin/sudo -E -p "Need to install Bundler for system ruby, password for sudo: " \
  /usr/bin/gem install bundler --no-rdoc --no-ri
}

# We don't want old config hanging around.

rm -rf .bundle/config
rm -rf .librarian/puppet/config

bundle install --binstubs bin --path .bundle --quiet "$@"


# Fix the binstubs to use system ruby
find bin -not -path 'bin/\.*' -type f -print0 | xargs -0 /usr/bin/sed -i '' 's|/usr/bin/env ruby|/usr/bin/ruby|g'
