#!/bin/sh
# Make sure all our local dependencies are available.

set -e

#Add fake group to fix GID/domain issues (https://github.com/boxen/our-boxen/issues/235)
GID="$(id -g)"
USERNAME="$(id -u -nr)"
if !(grep "$GID" /etc/group >/dev/null) ; then
  echo "Adding GID ($GID) for $USERNAME into /etc/group"
  sudo sh -c "echo $USERNAME:*:$GID:$USERNAME >> /etc/group"
fi

if [[ ! -e /opt/boxen/repo/.rubybin/bin/bundle ]]; then
  gem install --no-document --install-dir /opt/boxen/repo/.rubybin bundler
fi

# We don't want old config hanging around.

rm -rf .bundle/config
rm -rf .librarian/puppet/config

# Put xcrun shim on PATH if on MoLo
set +e
OSX_VERSION_CHECK=`sw_vers | grep ProductVersion | cut -f 2 -d ':'  | egrep '10\.8'`
if [ $? -eq 0 ]; then
  export PATH=$(pwd)/vendor/shims:$PATH
fi
set -e

CLT_VERSION=`pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | grep version | cut -f 2 -d ' ' | awk ' { print $1; } '`

/opt/boxen/repo/.rubybin/bin/bundle install --binstubs bin --path .bundle --quiet "$@"

