#!/usr/bin/env bash

xcode-select -p &>/dev/null
if [ -n $? ] ; then
    echo 'Please follow the prompt to install Xcode command line tools, then re-run this command'
    xcode-select --install
    exit 0
fi

set -e

sudo mkdir -p /opt/boxen
sudo chown ${USER}:staff /opt/boxen
git clone git://github.com/akerl-boxen/boxen /opt/boxen/repo
cd /opt/boxen/repo
exec ./script/boxen

