#!/usr/bin/env bash

echo "[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh" > ~/.profile

echo 'Checking for pending software updates'
softwareupdate -i -a

echo 'Checking for Xcode command line tools'
xcode-select -p &>/dev/null
if [ "$?" != "0" ] ; then
    echo 'Please follow the prompt to install Xcode command line tools, then re-run this command'
    xcode-select --install &>/dev/null
    exit 0
fi

set -e

sudo mkdir -p /opt/boxen
sudo chown ${USER}:staff /opt/boxen
git clone git://github.com/halyard/halyard /opt/boxen/repo
cd /opt/boxen/repo
exec ./script/boxen

