name: Build
on:
  pull_request:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
        fetch-depth: 0
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Build
      run: bundle exec rake
    - name: Post to hook-exporter
      run: ./.github/exporter.sh
      env:
        EXPORTER_TOKEN: ${{ secrets.EXPORTER_TOKEN }}
        JOB_STATUS: ${{ job.status }}
      if: ${{ always() }}
